language: python

install: "pip install -r ./requirements/requirements.txt"

node_js:
  - "stable"

before_script:
  - npm install -g grunt-cli
  - npm install
  - pip install tox

script:
  - npm test
  - pip install six
  - tox

after_success:
    - coveralls