language: python
node_js:
  - "stable"

branches:
  only:
    /*/

before_script:
  - npm install -g grunt-cli
  - npm install
  -rm -rf .tox
  - pip install -r requirements/dev_requirements.txt

script:
  - npm test
  - tox

after_success:
    - coveralls
