language: python
node_js:
  - "stable"
install:
  - pip install -r requirements/requirements.txt
before_script:
  - npm install -g grunt-cli
  - npm install
  - pip install tox

script:
  - npm test
  - tox

after_success:
    - coveralls
