language: python
node_js:
  - "stable"

before_script:
  - npm install -g grunt-cli bower
  - npm install
  - bower install
  - pip install tox

script:
  - npm test
  - tox

after_success:
    - coveralls
